platform :ios, '7.0'
 
pod 'AFNetworking', '2.5.1'
pod 'ReactiveCocoa', '2.1.8'
pod 'NSLogger'
pod 'pop', '~> 1.0'
pod 'Mantle'
pod 'MBProgressHUD'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'facebook-ios-sdk'
